services:
  vuln-tomcat:
    image: tomcat:9.0.76 # Index Digit: sha256:0d46b4fe76c6fb7142f54c9f2934c65ead7e8c505fe97291a9c3799da9ab3f13
    container_name: vuln-tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    environment:
      - TZ=UTC
    command: >
      bash -c "
        sed -i 's/readonly=\"true\"/readonly=\"false\"/' /usr/local/tomcat/webapps/manager/META-INF/context.xml || true &&
        sed -i 's/<servlet-name>default<\\/servlet-name>/&\\n<init-param>\\n<param-name>readonly<\\/param-name>\\n<param-value>false<\\/param-value>\\n<\\/init-param>/' /usr/local/tomcat/conf/web.xml &&
        catalina.sh run
      "